### ISSUE TITLE
Read from location 0000000000000040 caused an access violation.

### ISSUE THREAD

**Issue by joshkbaker** [keijiro/Smrvfx#31] opened 2021-09-22 13:49 UTC
Not totally sure if it's coming from this file but I was getting a an error causing Unity to crash.
Read from location 0000000000000040 caused an access violation.

I wasn't totally sure but my Visual Studio was pointing me to smrvfx?

**Comment by keijiro** [comment] 2021-09-22 13:57
I'm pretty sure that it's not related to Smrvfx because it doesn't contain any unmanaged code.
(Usually, this kind of crash is caused by unmanaged code like native plugins)

I'd recommend checking if you're using a native plugin.

By the way, now VFX Graph supports skinned mesh sampling. This means that you shouldn't use Smrvfx any more -- you can do the same thing with the built-in functionality.

**Comment by keijiro** [comment] 2021-09-22 13:57
I'm closing this issue now. Please feel free to reopen it for further problems.

**Closed as completed by keijiro** 2021-09-22 13:57 UTC
Labels: question

**Comment by joshkbaker** [comment] 2021-09-22 15:00
> native plugin

Is there anyway to check if my project is using native plugins. I'm trying to get to the root of this issue.

**Comment by keijiro** [comment] 2021-09-22 15:05
I'd recommend checking if the project contains unmanaged .dll files.

**Comment by joshkbaker** [comment] 2021-10-31 17:11
Hi Keijiro, it wasnt your asset. Apologies
