### ISSUE TITLE
New Issues on Terrain

### ISSUE THREAD

**Issue by Rimeo-hub** [keijiro/Smrvfx#29] opened 2021-03-24 19:57 UTC
There is an issue where the particle cannot be seen from any angle other than a particular angle when the object on which the particle occurs is moved onto the Terrain.

https://youtu.be/bV49gWqs618
https://youtu.be/_hmI6OIv79c

**Comment by keijiro** [comment] 2021-03-25 02:11
This is a duplicate of #19. Please check the workaround in my reply in the thread.

**Comment by keijiro** [comment] 2021-03-25 02:11
I'm closing this issue now. Please feel free to reopen it for further problems.

**Closed as completed by keijiro** 2021-03-25 02:11 UTC
Labels: question
