### ISSUE TITLE
Is there any way to bake the position map so the list of positions isn't random?

### ISSUE THREAD

**Issue by ADrozin** [keijiro/Smrvfx#14] opened 2019-11-02 13:07 UTC
I'd like to spawn the particles based on index, but the problem is that the 0 index is not directly next to the 1 index on the model. All of the positions are in random positions. I'd like to do sort of a slow fade of the mesh, but that isn't possible since the order of positions does not correlate with the actual distance and position of the verts on the mesh. 

Is there any way to do this? Thanks!

**Comment by keijiro** [comment] 2019-11-02 13:19
Actually it's not random. The order of vertices in the original mesh is kept in the baked position map. So if you managed to order the vertices in the original mesh (i.e. in the source fbx file) as you want, the position map will be ordered in the same way. I don't have any idea about how to make it consistently.

**Comment by keijiro** [comment] 2019-11-02 13:20
I'm closing this issue now as the problem is not actually relevant to the repository. Please feel free to reopen for further problems.

**Closed as completed by keijiro** 2019-11-02 13:19 UTC
Labels: question

**Comment by sergiobd** [comment] 2019-11-04 02:08
@ADrozin, if you want to do fade-in/out vertically/horizontally, maybe you could try to generate/kill the particles using an animated Kill(AABox).

**Comment by ADrozin** [comment] 2019-11-04 12:24
> @ADrozin, if you want to do fade-in/out vertically/horizontally, maybe you could try go generate/kill the particles using an animated Kill(AABox).

Alright so that will work! Didn't know about that node! Thanks.
